export type Locale = 'pt' | 'en' | 'es'

export const content = {
  pt: {
    locale: 'pt' as const,
    nav: {
      manifesto: 'Manifesto',
      services: 'O que fazemos',
      differential: 'Diferencial',
      partnership: 'Parceria',
      cta: 'Conversar',
    },
    hero: {
      eyebrow: 'WDT USA GROUP · Desde 2006',
      tagline: 'Tecnologia que vira',
      taglineGold: 'capital.',
      statement: 'Construímos negócios.',
      statementGold: 'Tecnologia é só uma das ferramentas.',
      proof: '20 anos. Embraer, Grupo Abril, Casacor. Um exit para o Grupo Globo em 2026.',
      sub: 'Onde a complexidade técnica encontra a receita real. Estratégia, sistemas, operação e IA aplicada — sob o mesmo teto, transformando código em escala e escala em capital.',
      ctaPrimary: 'Iniciar uma conversa',
      ctaSecondary: 'Ver o manifesto',
    },
    track: [
      { tag: 'DESDE 2006', t: '20 anos', d: 'de WDT no mercado, atendendo grupos como Embraer, Abril e Casacor' },
      { tag: '2021 – 2026', t: 'Abril → Globo', d: '5 anos liderando a tecnologia que viabilizou o exit para o Grupo Globo' },
      { tag: 'BRASIL → EUA', t: 'Expansão', d: 'apoiando empresas brasileiras que crescem rápido nos Estados Unidos' },
      { tag: 'IA APLICADA', t: 'Em produção', d: 'agentes inteligentes 24/7 em vendas, suporte e operação' },
    ],
    trustStrip: 'Construído para — e com —',
    trustNote: 'Liderança de tecnologia e transformação digital em grupos cujos exits, IPOs e operações dependeram — e dependem — de uma fundação técnica feita para durar.',
    signatureCase: {
      eyebrow: 'Caso assinatura · 2021 – 2026',
      h2a: 'Cinco anos de tecnologia.',
      h2b: 'Um exit para o',
      h2bGold: 'Grupo Globo.',
      p1: 'Por <strong>5 anos</strong> liderei a tecnologia e o digital do Grupo Abril durante a transformação mais profunda da sua história recente — modernizando plataformas, construindo a operação digital de marcas como Casacor, e migrando o grupo de uma estrutura editorial tradicional para uma operação de tecnologia que entrega resultado em capital.',
      p2: 'Em <strong>2026</strong>, esse trabalho viabilizou um dos maiores movimentos do mercado brasileiro de mídia: o exit do Grupo Abril com a aquisição pelo <strong>Grupo Globo</strong>. Tecnologia bem feita, no fim do dia, vira capital.',
      stats: [
        { n: '05', l: 'anos liderando a infra digital do Abril' },
        { n: '01', l: 'exit estratégico em 2026 para o Globo' },
        { n: '∞', l: 'plataformas, sistemas e produtos' },
        { n: 'CASACOR', l: 'entre as operações sustentadas' },
      ],
      lessonTag: 'A LIÇÃO',
      lesson: 'Exit de uma operação tradicional não acontece por sorte — acontece quando a fundação tecnológica é construída para sustentar o resultado, não para impressionar o slide.',
    },
    testimonial: {
      eyebrow: 'Testemunho',
      quote: 'Trabalhei com o Leandro durante toda a transformação digital do Grupo Abril. O que ele construiu não foi apenas tecnologia — foi a <strong>fundação operacional</strong> que sustentou a Casacor por anos e que, em 2026, viabilizou o melhor exit que o Grupo Abril já fez, com a aquisição pelo Grupo Globo. Tecnologia bem feita, no fim do dia, é <strong>capital</strong>.',
      name: 'Andre Secchin',
      role: 'CEO · Casacor',
    },
    manifesto: {
      eyebrow: 'Manifesto · 04 princípios',
      h2a: 'O que nos torna',
      h2aGold: 'diferentes',
      h2b: 'de tudo que está sendo vendido hoje como "IA".',
      items: [
        { n: '01', t: 'Negócio antes de tecnologia.', d: 'A IA mais bonita do mundo não vale nada sem venda, operação e cliente recorrente. A gente começa pelo fim — pelo resultado — e desenha a tecnologia para chegar lá.' },
        { n: '02', t: 'Estamos aqui antes do hype.', d: 'Construímos sistemas, automações e operações antes da IA virar moda. Vimos ondas chegarem e passarem. Saber distinguir o que vai durar do que é barulho é parte do nosso trabalho.' },
        { n: '03', t: 'Entregamos a operação inteira.', d: 'Estratégia, produto, código, IA, automação, suporte e venda — sob o mesmo teto. Nada de empurrar o cliente entre fornecedores. Nada de "depois disso, contrate outra empresa".' },
        { n: '04', t: 'Parceria proporcional ao valor entregue.', d: 'Trabalhamos com modelos claros: cliente, parceiro comercial, parceiro estratégico, investidor ou sócio executivo. Cada relação é justa, transparente e proporcional ao que cada lado entrega.' },
      ],
    },
    services: {
      eyebrow: 'O que fazemos',
      h2a: 'Seis frentes',
      h2aGold: 'conectadas.',
      h2b: 'Uma única operação.',
      sub: 'Não somos especialistas em uma única peça do quebra-cabeça. Construímos a operação inteira — da estratégia ao código, do agente de IA à esteira de venda, do produto à recorrência. É isso que permite entregar resultado de verdade, não relatório.',
      items: [
        { title: 'Inteligência Artificial Aplicada', desc: 'Agentes que vendem, qualificam, atendem e operam — integrados aos sistemas do cliente. IA que não é demo, é receita.', bullets: ['Agentes de venda e suporte', 'IA conectada a CRM, ERP e WhatsApp', 'Modelos com governança e contexto'] },
        { title: 'Sistemas e Plataformas Sob Medida', desc: 'Web, mobile, dashboards, ERPs internos, marketplaces. Entregues como produto pronto para escalar — não como protótipo.', bullets: ['Arquitetura cloud-first', 'UX e UI executiva', 'Operação 24/7 incluída'] },
        { title: 'Automação Comercial e Operacional', desc: 'Esteiras de venda, qualificação, follow-up, cobrança, pós-venda. Trabalho repetitivo vira fluxo automático e mensurável.', bullets: ['Pipelines integrados', 'Disparos por canal certo', 'Métricas em tempo real'] },
        { title: 'Estratégia de Produto e Vendas', desc: 'Antes do código, o jogo. Posicionamento, oferta, precificação, funil. Tecnologia só funciona em cima de estratégia certa.', bullets: ['Diagnóstico do funil', 'Construção de oferta', 'Roadmap comercial'] },
        { title: 'Verticais e Operações Próprias', desc: 'Quando faz sentido, montamos a vertical inteira — produto, marca, comercial, atendimento, IA — em parceria com quem traz o mercado.', bullets: ['Operações white-label', 'Parcerias com revenue share', 'Modelos de joint venture'] },
        { title: 'Consultoria Executiva em Tecnologia', desc: 'Para empresas que precisam decidir o que construir, comprar ou parar. Sem viés de fornecedor — só clareza sobre o que entrega resultado.', bullets: ['Auditoria de stack', 'Definição de prioridades', 'Implantação acompanhada'] },
      ],
    },
    differential: {
      eyebrow: 'Diferencial competitivo',
      h2a: 'O mercado vende',
      h2aGold: 'promessa.',
      h2b: 'A WDT entrega',
      h2bGold: 'resultado.',
      headerLeft: 'Maioria do mercado',
      headerRight: 'WDT USA GROUP',
      rows: [
        { others: 'Vendem ferramentas e API de IA prontas', us: 'Entregamos negócio funcionando ponta a ponta' },
        { others: 'Cobram por hora, projeto ou consumo', us: 'Cobramos por resultado, recorrência e operação' },
        { others: 'Lançam protótipos e demos bonitos', us: 'Botamos em produção, suporte e escala' },
        { others: 'Aparecem com o hype, somem na próxima moda', us: 'Estamos no mercado há mais de 20 anos' },
        { others: 'Empurram o cliente entre vários fornecedores', us: 'Operação inteira sob o mesmo teto' },
      ],
    },
    audience: {
      eyebrow: 'Para quem é a WDT',
      h2a: 'Três tipos de relação,',
      h2aGold: 'uma única regra:',
      h2b: 'clareza, performance e proporcionalidade.',
      cards: [
        { tag: 'Para empresários', t: 'Negócios que querem crescer — inclusive cruzando para os EUA', d: 'Empresas estabelecidas que precisam digitalizar, automatizar, vender mais e operar com IA — incluindo brasileiras escalando rápido nos Estados Unidos, onde execução decide quem cresce.', cta: 'Quero crescer' },
        { tag: 'Para parceiros', t: 'Quem traz mercado, abre porta ou desenvolve vertical', d: 'Parceiros comerciais, estratégicos ou de projeto que querem construir operação conjunta — com modelo claro de remuneração e participação.', cta: 'Quero construir junto' },
        { tag: 'Para investidores', t: 'Capital que busca tese real e governança', d: 'Investidores que valorizam mais de duas décadas de execução, time já formado e operação que gera receita — não só apresentação.', cta: 'Quero entender a tese' },
      ],
    },
    process: {
      eyebrow: 'Como trabalhamos',
      h2a: 'Quatro etapas.',
      h2aGold: 'Zero teatro.',
      steps: [
        { n: '01', t: 'Conversa inicial', d: 'Entender o negócio, o mercado e o resultado esperado. Sem briefing genérico, sem proposta-modelo.' },
        { n: '02', t: 'Diagnóstico e desenho', d: 'Mapeamos o funil, a operação e a stack atual. Desenhamos o caminho mais curto até o resultado.' },
        { n: '03', t: 'Execução com entrega contínua', d: 'Construímos em ciclos curtos com entrega real em produção — não em apresentação de slides.' },
        { n: '04', t: 'Operação e escala', d: 'Suporte, ajuste, otimização. Tecnologia que entra em produção precisa rodar 24/7 — e a gente roda.' },
      ],
    },
    leadership: {
      eyebrow: 'Fundadores · Brasil & Estados Unidos',
      h2a: 'Quem está',
      h2aGold: 'à frente',
      sub: 'Dois sócios fundadores. Duas frentes — Brasil e Estados Unidos. Uma mesma filosofia: tecnologia, operação e relacionamento que viram capital.',
      founders: [
        {
          initials: 'LM',
          first: 'Leandro',
          last: 'Mesquita',
          role: 'Founder & CEO · Brasil',
          flag: 'Brasil',
          bio: [
            'Há mais de <strong>20 anos no mercado</strong>, à frente da WDT, liderando tecnologia, produto e operação digital em grupos como <strong>Embraer</strong>, <strong>Grupo Abril</strong> e <strong>Casacor</strong>.',
            'Nos <strong>últimos 5 anos</strong>, conduziu a transformação digital do Grupo Abril — construindo a fundação técnica que sustentou marcas como Casacor e, em 2026, viabilizou o exit do grupo com a aquisição pelo <strong>Grupo Globo</strong>.',
            'Hoje, lidera a WDT na fronteira tecnológica: <em>tecnologia que vira capital</em>.',
          ],
        },
        {
          initials: 'RL',
          first: 'Rodrigo',
          last: 'Lucas',
          role: 'Co-founder · WDT USA',
          flag: 'Estados Unidos',
          bio: [
            'Empresário brasileiro radicado nos Estados Unidos. Construiu — do zero — a <strong>Fenix Mart Solution</strong>, uma das maiores operações de limpeza de carpetes e estofados de <strong>Orlando, Flórida</strong>.',
            'À frente do movimento <strong>Amigos nos EUA</strong>, lidera uma rede de empresários brasileiros que abrem, estruturam e escalam negócios em solo americano — conectando capital, mercado e operação.',
            'Na WDT, é a ponta operacional da fronteira <strong>Brasil → Estados Unidos</strong>: a inteligência de quem opera, contrata e vende todos os dias no maior mercado consumidor do mundo.',
          ],
        },
      ],
    },
    cta: {
      eyebrow: 'Vamos conversar',
      h2a: 'Se a IA é o tema da década,',
      h2aGold: 'o resultado é a única coisa que importa.',
      sub: 'Marque uma conversa de 30 minutos diretamente com <strong>Leandro Mesquita</strong>, founder & CEO da WDT USA GROUP. Sem apresentação genérica, sem proposta-modelo. Você fala — eu escuto, devolvo clareza e, se fizer sentido para os dois lados, começamos a construir.',
      cardEyebrow: 'Próximo passo',
      cardBullets: [
        'Conversa direta com Leandro Mesquita',
        '30 minutos, sem compromisso',
        'Diagnóstico inicial sem custo',
        'Resposta em até 1 dia útil',
      ],
      cardCta: 'Conversar com Leandro',
      cardOr: 'ou envie direto para',
    },
    footer: {
      tagline: 'Tecnologia que vira negócio. Há mais de 20 anos transformando estratégia, código e IA em receita real, operação que escala e cliente recorrente.',
      mapTitle: 'Mapa do site',
      contactTitle: 'Contato',
      contactItems: [
        'leandro@wdtgroup.com',
        'Conversa direta com Leandro Mesquita',
        'Resposta em até 1 dia útil · Brasil e EUA',
      ],
      since: '© WDT USA GROUP · Desde 2006',
      values: 'clareza · performance · proporcionalidade',
    },
  },
  // ============================================================
  // ENGLISH
  // ============================================================
  en: {
    locale: 'en' as const,
    nav: {
      manifesto: 'Manifesto',
      services: 'What we do',
      differential: 'Edge',
      partnership: 'Partnership',
      cta: 'Talk to us',
    },
    hero: {
      eyebrow: 'WDT USA GROUP · Since 2006',
      tagline: 'Technology that becomes',
      taglineGold: 'capital.',
      statement: 'We build businesses.',
      statementGold: 'Technology is just one of the tools.',
      proof: '20 years. Embraer, Grupo Abril, Casacor. An exit to Grupo Globo in 2026.',
      sub: 'Where technical complexity meets real revenue. Strategy, systems, operations and applied AI — under one roof, turning code into scale and scale into capital.',
      ctaPrimary: 'Start a conversation',
      ctaSecondary: 'Read the manifesto',
    },
    track: [
      { tag: 'SINCE 2006', t: '20 years', d: 'of WDT in the market, serving groups like Embraer, Abril and Casacor' },
      { tag: '2021 – 2026', t: 'Abril → Globo', d: '5 years leading the technology that enabled the exit to Grupo Globo' },
      { tag: 'BRAZIL → US', t: 'Expansion', d: 'supporting Brazilian companies scaling fast in the United States' },
      { tag: 'APPLIED AI', t: 'In production', d: 'intelligent agents 24/7 in sales, support and operations' },
    ],
    trustStrip: 'Built for — and with —',
    trustNote: 'Technology and digital transformation leadership in groups whose exits, IPOs and operations relied — and rely — on a technical foundation built to last.',
    signatureCase: {
      eyebrow: 'Signature case · 2021 – 2026',
      h2a: 'Five years of technology.',
      h2b: 'One exit to',
      h2bGold: 'Grupo Globo.',
      p1: 'For <strong>5 years</strong> I led the technology and digital operations of Grupo Abril during the deepest transformation of its recent history — modernizing platforms, building the digital operation of brands like Casacor, and migrating the group from a traditional editorial structure to a technology operation that delivers results in capital.',
      p2: 'In <strong>2026</strong>, this work enabled one of the largest moves in the Brazilian media market: the exit of Grupo Abril with the acquisition by <strong>Grupo Globo</strong>. Well-built technology, at the end of the day, becomes capital.',
      stats: [
        { n: '05', l: 'years leading Abril\'s digital infrastructure' },
        { n: '01', l: 'strategic exit in 2026 to Globo' },
        { n: '∞', l: 'platforms, systems and products' },
        { n: 'CASACOR', l: 'among the operations sustained' },
      ],
      lessonTag: 'THE LESSON',
      lesson: 'A traditional operation\'s exit doesn\'t happen by luck — it happens when the technological foundation is built to sustain the result, not to impress the slide.',
    },
    testimonial: {
      eyebrow: 'Testimonial',
      quote: "I worked with Leandro throughout the entire digital transformation of Grupo Abril. What he built was not just technology — it was the <strong>operational foundation</strong> that sustained Casacor for years and that, in 2026, enabled the best exit Grupo Abril has ever done, with the acquisition by Grupo Globo. Well-built technology, at the end of the day, is <strong>capital</strong>.",
      name: 'Andre Secchin',
      role: 'CEO · Casacor',
    },
    manifesto: {
      eyebrow: 'Manifesto · 04 principles',
      h2a: 'What makes us',
      h2aGold: 'different',
      h2b: 'from everything being sold today as "AI".',
      items: [
        { n: '01', t: 'Business before technology.', d: "The most beautiful AI in the world is worth nothing without sales, operations and recurring customers. We start from the end — from the result — and design the technology to get there." },
        { n: '02', t: 'We were here before the hype.', d: "We've built systems, automation and operations long before AI became fashion. We've seen waves come and go. Knowing how to distinguish what will last from what is noise is part of our work." },
        { n: '03', t: 'We deliver the entire operation.', d: 'Strategy, product, code, AI, automation, support and sales — under one roof. No pushing the customer between vendors. No "after this, hire another company".' },
        { n: '04', t: 'Partnership proportional to value delivered.', d: "We work with clear models: client, commercial partner, strategic partner, investor or executive partner. Each relationship is fair, transparent and proportional to what each side delivers." },
      ],
    },
    services: {
      eyebrow: 'What we do',
      h2a: 'Six',
      h2aGold: 'connected fronts.',
      h2b: 'One single operation.',
      sub: "We're not specialists in a single piece of the puzzle. We build the entire operation — from strategy to code, from AI agent to sales pipeline, from product to recurrence. That's what allows us to deliver real results, not reports.",
      items: [
        { title: 'Applied Artificial Intelligence', desc: "Agents that sell, qualify, serve and operate — integrated with the client's systems. AI that isn't a demo, but revenue.", bullets: ['Sales and support agents', 'AI connected to CRM, ERP and WhatsApp', 'Models with governance and context'] },
        { title: 'Custom Systems and Platforms', desc: 'Web, mobile, dashboards, internal ERPs, marketplaces. Delivered as products ready to scale — not as prototypes.', bullets: ['Cloud-first architecture', 'Executive UX and UI', '24/7 operation included'] },
        { title: 'Commercial and Operational Automation', desc: 'Sales pipelines, qualification, follow-up, billing, post-sales. Repetitive work becomes automatic, measurable flow.', bullets: ['Integrated pipelines', 'Right-channel triggers', 'Real-time metrics'] },
        { title: 'Product and Sales Strategy', desc: 'Before the code, the game. Positioning, offer, pricing, funnel. Technology only works on top of the right strategy.', bullets: ['Funnel diagnosis', 'Offer construction', 'Commercial roadmap'] },
        { title: 'Verticals and Own Operations', desc: 'When it makes sense, we build the entire vertical — product, brand, commercial, support, AI — in partnership with those who bring the market.', bullets: ['White-label operations', 'Revenue share partnerships', 'Joint venture models'] },
        { title: 'Executive Technology Consulting', desc: 'For companies that need to decide what to build, buy or stop. No vendor bias — just clarity about what delivers results.', bullets: ['Stack audit', 'Priority definition', 'Guided implementation'] },
      ],
    },
    differential: {
      eyebrow: 'Competitive edge',
      h2a: 'The market sells',
      h2aGold: 'promise.',
      h2b: 'WDT delivers',
      h2bGold: 'results.',
      headerLeft: 'Most of the market',
      headerRight: 'WDT USA GROUP',
      rows: [
        { others: 'Sells ready-made AI tools and APIs', us: 'Delivers business working end-to-end' },
        { others: 'Charges by hour, project or consumption', us: 'Charges for results, recurrence and operation' },
        { others: 'Launches prototypes and pretty demos', us: 'Puts in production, support and scale' },
        { others: 'Shows up with hype, disappears with the next trend', us: "We've been in the market for over 20 years" },
        { others: 'Pushes clients between multiple vendors', us: 'Entire operation under one roof' },
      ],
    },
    audience: {
      eyebrow: 'Who WDT is for',
      h2a: 'Three types of relationship,',
      h2aGold: 'one single rule:',
      h2b: 'clarity, performance and proportionality.',
      cards: [
        { tag: 'For entrepreneurs', t: 'Businesses that want to grow — including crossing into the US', d: 'Established companies that need to digitize, automate, sell more and operate with AI — including Brazilians scaling fast in the United States, where execution decides who grows.', cta: 'I want to grow' },
        { tag: 'For partners', t: 'Those who bring market, open doors or develop verticals', d: 'Commercial, strategic or project partners who want to build joint operations — with clear models for compensation and participation.', cta: 'I want to build together' },
        { tag: 'For investors', t: 'Capital that seeks real thesis and governance', d: 'Investors who value more than two decades of execution, a formed team and operations that generate revenue — not just presentations.', cta: 'I want to understand the thesis' },
      ],
    },
    process: {
      eyebrow: 'How we work',
      h2a: 'Four steps.',
      h2aGold: 'Zero theater.',
      steps: [
        { n: '01', t: 'Initial conversation', d: 'Understanding the business, the market and the expected result. No generic briefing, no template proposal.' },
        { n: '02', t: 'Diagnosis and design', d: 'We map the funnel, the operation and the current stack. We design the shortest path to the result.' },
        { n: '03', t: 'Execution with continuous delivery', d: 'We build in short cycles with real production delivery — not in slide presentations.' },
        { n: '04', t: 'Operation and scale', d: "Support, adjustment, optimization. Technology that goes into production needs to run 24/7 — and we run it." },
      ],
    },
    leadership: {
      eyebrow: 'Founders · Brazil & United States',
      h2a: 'Who is',
      h2aGold: 'leading',
      sub: 'Two founding partners. Two fronts — Brazil and the United States. The same philosophy: technology, operation and relationships that turn into capital.',
      founders: [
        {
          initials: 'LM',
          first: 'Leandro',
          last: 'Mesquita',
          role: 'Founder & CEO · Brazil',
          flag: 'Brazil',
          bio: [
            'For over <strong>20 years in the market</strong>, leading WDT, heading technology, product and digital operations in groups such as <strong>Embraer</strong>, <strong>Grupo Abril</strong> and <strong>Casacor</strong>.',
            'In the <strong>last 5 years</strong>, led the digital transformation of Grupo Abril — building the technical foundation that sustained brands like Casacor and, in 2026, enabled the group\'s exit with the acquisition by <strong>Grupo Globo</strong>.',
            'Today leads WDT at the technological frontier: <em>technology that becomes capital</em>.',
          ],
        },
        {
          initials: 'RL',
          first: 'Rodrigo',
          last: 'Lucas',
          role: 'Co-founder · WDT USA',
          flag: 'United States',
          bio: [
            'Brazilian entrepreneur based in the United States. Built — from zero — <strong>Fenix Mart Solution</strong>, one of the largest carpet and upholstery cleaning operations in <strong>Orlando, Florida</strong>.',
            'Leading the <strong>Amigos nos EUA</strong> movement, heads a network of Brazilian entrepreneurs who open, structure and scale businesses in American soil — connecting capital, market and operation.',
            'At WDT, is the operational edge of the <strong>Brazil → United States</strong> frontier: the intelligence of those who operate, hire and sell every day in the largest consumer market in the world.',
          ],
        },
      ],
    },
    cta: {
      eyebrow: "Let's talk",
      h2a: 'If AI is the topic of the decade,',
      h2aGold: 'results are the only thing that matter.',
      sub: 'Schedule a 30-minute conversation directly with <strong>Leandro Mesquita</strong>, founder & CEO of WDT USA GROUP. No generic presentation, no template proposal. You speak — I listen, return clarity, and if it makes sense for both sides, we start building.',
      cardEyebrow: 'Next step',
      cardBullets: [
        'Direct conversation with Leandro Mesquita',
        '30 minutes, no commitment',
        'Initial diagnosis at no cost',
        'Reply within 1 business day',
      ],
      cardCta: 'Talk to Leandro',
      cardOr: 'or send directly to',
    },
    footer: {
      tagline: 'Technology that becomes business. For over 20 years transforming strategy, code and AI into real revenue, scalable operations and recurring customers.',
      mapTitle: 'Site map',
      contactTitle: 'Contact',
      contactItems: [
        'leandro@wdtgroup.com',
        'Direct conversation with Leandro Mesquita',
        'Reply within 1 business day · Brazil and US',
      ],
      since: '© WDT USA GROUP · Since 2006',
      values: 'clarity · performance · proportionality',
    },
  },
  // ============================================================
  // ESPAÑOL
  // ============================================================
  es: {
    locale: 'es' as const,
    nav: {
      manifesto: 'Manifiesto',
      services: 'Qué hacemos',
      differential: 'Diferencial',
      partnership: 'Alianza',
      cta: 'Conversar',
    },
    hero: {
      eyebrow: 'WDT USA GROUP · Desde 2006',
      tagline: 'Tecnología que se vuelve',
      taglineGold: 'capital.',
      statement: 'Construimos negocios.',
      statementGold: 'La tecnología es solo una de las herramientas.',
      proof: '20 años. Embraer, Grupo Abril, Casacor. Una salida hacia Grupo Globo en 2026.',
      sub: 'Donde la complejidad técnica encuentra los ingresos reales. Estrategia, sistemas, operación e IA aplicada — bajo el mismo techo, transformando código en escala y escala en capital.',
      ctaPrimary: 'Iniciar una conversación',
      ctaSecondary: 'Ver el manifiesto',
    },
    track: [
      { tag: 'DESDE 2006', t: '20 años', d: 'de WDT en el mercado, atendiendo grupos como Embraer, Abril y Casacor' },
      { tag: '2021 – 2026', t: 'Abril → Globo', d: '5 años liderando la tecnología que viabilizó la salida hacia Grupo Globo' },
      { tag: 'BRASIL → EE.UU.', t: 'Expansión', d: 'apoyando empresas brasileñas que crecen rápido en Estados Unidos' },
      { tag: 'IA APLICADA', t: 'En producción', d: 'agentes inteligentes 24/7 en ventas, soporte y operación' },
    ],
    trustStrip: 'Construido para — y con —',
    trustNote: 'Liderazgo de tecnología y transformación digital en grupos cuyas salidas, IPOs y operaciones dependieron — y dependen — de una fundación técnica hecha para durar.',
    signatureCase: {
      eyebrow: 'Caso emblema · 2021 – 2026',
      h2a: 'Cinco años de tecnología.',
      h2b: 'Una salida hacia el',
      h2bGold: 'Grupo Globo.',
      p1: 'Durante <strong>5 años</strong> lideré la tecnología y lo digital del Grupo Abril durante la transformación más profunda de su historia reciente — modernizando plataformas, construyendo la operación digital de marcas como Casacor, y migrando al grupo de una estructura editorial tradicional hacia una operación de tecnología que entrega resultado en capital.',
      p2: 'En <strong>2026</strong>, este trabajo viabilizó uno de los movimientos más grandes del mercado brasileño de medios: la salida del Grupo Abril con la adquisición por el <strong>Grupo Globo</strong>. La tecnología bien hecha, al final del día, se convierte en capital.',
      stats: [
        { n: '05', l: 'años liderando la infraestructura digital de Abril' },
        { n: '01', l: 'salida estratégica en 2026 hacia Globo' },
        { n: '∞', l: 'plataformas, sistemas y productos' },
        { n: 'CASACOR', l: 'entre las operaciones sostenidas' },
      ],
      lessonTag: 'LA LECCIÓN',
      lesson: 'La salida de una operación tradicional no ocurre por suerte — ocurre cuando la fundación tecnológica está construida para sostener el resultado, no para impresionar el slide.',
    },
    testimonial: {
      eyebrow: 'Testimonio',
      quote: 'Trabajé con Leandro durante toda la transformación digital del Grupo Abril. Lo que él construyó no fue solo tecnología — fue la <strong>fundación operacional</strong> que sostuvo a Casacor durante años y que, en 2026, viabilizó la mejor salida que el Grupo Abril ya hizo, con la adquisición por el Grupo Globo. La tecnología bien hecha, al final del día, es <strong>capital</strong>.',
      name: 'Andre Secchin',
      role: 'CEO · Casacor',
    },
    manifesto: {
      eyebrow: 'Manifiesto · 04 principios',
      h2a: 'Lo que nos hace',
      h2aGold: 'diferentes',
      h2b: 'de todo lo que se vende hoy como "IA".',
      items: [
        { n: '01', t: 'Negocio antes de tecnología.', d: 'La IA más bonita del mundo no vale nada sin venta, operación y cliente recurrente. Empezamos por el final — por el resultado — y diseñamos la tecnología para llegar allí.' },
        { n: '02', t: 'Estamos aquí antes del hype.', d: 'Construimos sistemas, automatizaciones y operaciones antes de que la IA se volviera moda. Vimos olas llegar y pasar. Saber distinguir lo que va a durar de lo que es ruido es parte de nuestro trabajo.' },
        { n: '03', t: 'Entregamos la operación entera.', d: 'Estrategia, producto, código, IA, automatización, soporte y venta — bajo el mismo techo. Nada de empujar al cliente entre proveedores. Nada de "después de esto, contrate otra empresa".' },
        { n: '04', t: 'Alianza proporcional al valor entregado.', d: 'Trabajamos con modelos claros: cliente, socio comercial, socio estratégico, inversionista o socio ejecutivo. Cada relación es justa, transparente y proporcional a lo que cada lado entrega.' },
      ],
    },
    services: {
      eyebrow: 'Qué hacemos',
      h2a: 'Seis frentes',
      h2aGold: 'conectados.',
      h2b: 'Una sola operación.',
      sub: 'No somos especialistas en una sola pieza del rompecabezas. Construimos la operación entera — de la estrategia al código, del agente de IA al embudo de venta, del producto a la recurrencia. Eso es lo que permite entregar resultado de verdad, no informe.',
      items: [
        { title: 'Inteligencia Artificial Aplicada', desc: 'Agentes que venden, califican, atienden y operan — integrados a los sistemas del cliente. IA que no es demo, es ingreso.', bullets: ['Agentes de venta y soporte', 'IA conectada a CRM, ERP y WhatsApp', 'Modelos con gobernanza y contexto'] },
        { title: 'Sistemas y Plataformas a Medida', desc: 'Web, mobile, dashboards, ERPs internos, marketplaces. Entregados como producto listo para escalar — no como prototipo.', bullets: ['Arquitectura cloud-first', 'UX y UI ejecutiva', 'Operación 24/7 incluida'] },
        { title: 'Automatización Comercial y Operacional', desc: 'Embudos de venta, calificación, follow-up, cobranza, postventa. El trabajo repetitivo se vuelve flujo automático y medible.', bullets: ['Pipelines integrados', 'Disparos por canal correcto', 'Métricas en tiempo real'] },
        { title: 'Estrategia de Producto y Ventas', desc: 'Antes del código, el juego. Posicionamiento, oferta, precios, embudo. La tecnología solo funciona sobre la estrategia correcta.', bullets: ['Diagnóstico del embudo', 'Construcción de oferta', 'Roadmap comercial'] },
        { title: 'Verticales y Operaciones Propias', desc: 'Cuando tiene sentido, montamos la vertical entera — producto, marca, comercial, atención, IA — en alianza con quien trae el mercado.', bullets: ['Operaciones white-label', 'Alianzas con revenue share', 'Modelos de joint venture'] },
        { title: 'Consultoría Ejecutiva en Tecnología', desc: 'Para empresas que necesitan decidir qué construir, comprar o detener. Sin sesgo de proveedor — solo claridad sobre lo que entrega resultado.', bullets: ['Auditoría de stack', 'Definición de prioridades', 'Implementación acompañada'] },
      ],
    },
    differential: {
      eyebrow: 'Diferencial competitivo',
      h2a: 'El mercado vende',
      h2aGold: 'promesa.',
      h2b: 'WDT entrega',
      h2bGold: 'resultado.',
      headerLeft: 'Mayoría del mercado',
      headerRight: 'WDT USA GROUP',
      rows: [
        { others: 'Venden herramientas y APIs de IA listas', us: 'Entregamos negocio funcionando de punta a punta' },
        { others: 'Cobran por hora, proyecto o consumo', us: 'Cobramos por resultado, recurrencia y operación' },
        { others: 'Lanzan prototipos y demos bonitos', us: 'Ponemos en producción, soporte y escala' },
        { others: 'Aparecen con el hype, desaparecen con la próxima moda', us: 'Estamos en el mercado hace más de 20 años' },
        { others: 'Empujan al cliente entre varios proveedores', us: 'Operación entera bajo el mismo techo' },
      ],
    },
    audience: {
      eyebrow: 'Para quién es WDT',
      h2a: 'Tres tipos de relación,',
      h2aGold: 'una sola regla:',
      h2b: 'claridad, desempeño y proporcionalidad.',
      cards: [
        { tag: 'Para empresarios', t: 'Negocios que quieren crecer — incluso cruzando hacia EE.UU.', d: 'Empresas establecidas que necesitan digitalizar, automatizar, vender más y operar con IA — incluyendo brasileños escalando rápido en Estados Unidos, donde la ejecución decide quién crece.', cta: 'Quiero crecer' },
        { tag: 'Para socios', t: 'Quienes traen mercado, abren puertas o desarrollan verticales', d: 'Socios comerciales, estratégicos o de proyecto que quieren construir operación conjunta — con modelo claro de remuneración y participación.', cta: 'Quiero construir junto' },
        { tag: 'Para inversionistas', t: 'Capital que busca tesis real y gobernanza', d: 'Inversionistas que valoran más de dos décadas de ejecución, equipo ya formado y operación que genera ingreso — no solo presentación.', cta: 'Quiero entender la tesis' },
      ],
    },
    process: {
      eyebrow: 'Cómo trabajamos',
      h2a: 'Cuatro etapas.',
      h2aGold: 'Cero teatro.',
      steps: [
        { n: '01', t: 'Conversación inicial', d: 'Entender el negocio, el mercado y el resultado esperado. Sin briefing genérico, sin propuesta-modelo.' },
        { n: '02', t: 'Diagnóstico y diseño', d: 'Mapeamos el embudo, la operación y el stack actual. Diseñamos el camino más corto hasta el resultado.' },
        { n: '03', t: 'Ejecución con entrega continua', d: 'Construimos en ciclos cortos con entrega real en producción — no en presentación de slides.' },
        { n: '04', t: 'Operación y escala', d: 'Soporte, ajuste, optimización. La tecnología que entra en producción necesita correr 24/7 — y la corremos.' },
      ],
    },
    leadership: {
      eyebrow: 'Fundadores · Brasil y Estados Unidos',
      h2a: 'Quién está',
      h2aGold: 'al frente',
      sub: 'Dos socios fundadores. Dos frentes — Brasil y Estados Unidos. La misma filosofía: tecnología, operación y relacionamiento que se convierten en capital.',
      founders: [
        {
          initials: 'LM',
          first: 'Leandro',
          last: 'Mesquita',
          role: 'Founder & CEO · Brasil',
          flag: 'Brasil',
          bio: [
            'Hace más de <strong>20 años en el mercado</strong>, al frente de WDT, liderando tecnología, producto y operación digital en grupos como <strong>Embraer</strong>, <strong>Grupo Abril</strong> y <strong>Casacor</strong>.',
            'En los <strong>últimos 5 años</strong>, condujo la transformación digital del Grupo Abril — construyendo la fundación técnica que sostuvo marcas como Casacor y, en 2026, viabilizó la salida del grupo con la adquisición por el <strong>Grupo Globo</strong>.',
            'Hoy, lidera WDT en la frontera tecnológica: <em>tecnología que se convierte en capital</em>.',
          ],
        },
        {
          initials: 'RL',
          first: 'Rodrigo',
          last: 'Lucas',
          role: 'Co-founder · WDT USA',
          flag: 'Estados Unidos',
          bio: [
            'Empresario brasileño radicado en Estados Unidos. Construyó — desde cero — <strong>Fenix Mart Solution</strong>, una de las mayores operaciones de limpieza de alfombras y tapizados de <strong>Orlando, Florida</strong>.',
            'Al frente del movimiento <strong>Amigos nos EUA</strong>, lidera una red de empresarios brasileños que abren, estructuran y escalan negocios en suelo americano — conectando capital, mercado y operación.',
            'En WDT, es la punta operacional de la frontera <strong>Brasil → Estados Unidos</strong>: la inteligencia de quien opera, contrata y vende todos los días en el mayor mercado consumidor del mundo.',
          ],
        },
      ],
    },
    cta: {
      eyebrow: 'Conversemos',
      h2a: 'Si la IA es el tema de la década,',
      h2aGold: 'el resultado es la única cosa que importa.',
      sub: 'Agenda una conversación de 30 minutos directamente con <strong>Leandro Mesquita</strong>, founder & CEO de WDT USA GROUP. Sin presentación genérica, sin propuesta-modelo. Tú hablas — yo escucho, devuelvo claridad y, si tiene sentido para los dos lados, empezamos a construir.',
      cardEyebrow: 'Próximo paso',
      cardBullets: [
        'Conversación directa con Leandro Mesquita',
        '30 minutos, sin compromiso',
        'Diagnóstico inicial sin costo',
        'Respuesta en hasta 1 día hábil',
      ],
      cardCta: 'Conversar con Leandro',
      cardOr: 'o envía directo a',
    },
    footer: {
      tagline: 'Tecnología que se convierte en negocio. Hace más de 20 años transformando estrategia, código e IA en ingresos reales, operación que escala y cliente recurrente.',
      mapTitle: 'Mapa del sitio',
      contactTitle: 'Contacto',
      contactItems: [
        'leandro@wdtgroup.com',
        'Conversación directa con Leandro Mesquita',
        'Respuesta en hasta 1 día hábil · Brasil y EE.UU.',
      ],
      since: '© WDT USA GROUP · Desde 2006',
      values: 'claridad · desempeño · proporcionalidad',
    },
  },
}

export type WDTContent = typeof content.pt
